language: node_js
node_js:
  - "8"
script:
    - yarn coverage
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  - provider: script
    script: chmod +x ./node_modules/@boldgrid/wordpress-tag-sync/release.sh && ./node_modules/@boldgrid/wordpress-tag-sync/release.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "boldgrid-easy-seo.zip"
    skip_cleanup: true
    on:
      tags: true
